name: mysocial_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  http: ^1.2.1
  get_cli: ^1.8.1
  hive_flutter: ^1.1.0
  logger: ^2.2.0
  get_storage: ^2.1.1
  fluttertoast: ^8.2.5
  lazy_load_indexed_stack: ^1.1.0
  shimmer: ^3.0.0
  gap: ^3.0.1
  hive: ^2.2.3
  connectivity_plus: ^5.0.2
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Bold.ttf
        - asset: assets/fonts/Comfortaa-Light.ttf
        - asset: assets/fonts/Comfortaa-Medium.ttf
        - asset: assets/fonts/Comfortaa-Regular.ttf
        - asset: assets/fonts/Comfortaa-SemiBold.ttf
